### ISSUE TITLE
Can't make RGB Steel blocks

### ISSUE THREAD

**Issue by jaredniegas** [SpaceDave1337/dbExtended#1]
I'm on the latest version of the mod.
I can't make any of the RGB steel blocks and they have no recipes.

**Comment by SpaceDave1337** [comment]
They were a half baked idea, upon further consideration, they should be removed because of photosensitive individuals.

Hence, it is intended behaviour, they'll be removed from the next DBE Update anyways.

**Comment by jaredniegas** [comment]
No worries, I haven't played with the mod in a while and I had my fun with it.I understand why this change needs to be done. :)
    On Saturday, September 2, 2023 at 11:27:29 PM GMT+8, SpaceDave1337 ***@***.***> wrote:  
 
 


Closed #1 as not planned.
