### ISSUE TITLE
Unable to make Steel in 1.20.1

### ISSUE THREAD

**Issue by donottype** [SpaceDave1337/dbExtended#2]
I can't make steel in 1.20.1 in survival. I love this mod a lot but I can't use the most used material to build with on the latest version D:

**Comment by SpaceDave1337** [comment]
I am not completely sure why this is happening, as I did not make the 1.20.1 version, xRhys, the maintainer uploaded it. Though this should probably stop being an issue when DBE Update 6 is released, which might take a bit, sorry.
